### ISSUE TITLE
OT: Move JS error logging services gist to GitHub repo?

### ISSUE THREAD

**Issue by dandv** [cheeaun/life#54]
Hi Lim,

Thanks for compiling available JavaScript error logging services at https://gist.github.com/cheeaun/5835757.

As you might know, [the OP of gists isn't notified of comments on the gist](https://github.com/isaacs/github/issues/21). Also, users can't contribute changes.

Would you consider moving that gist to a regular repo with just one .md file?

**Comment by cheeaun** [comment]
Hey, sorry for the late response. I've finally moved it into a repo here: <https://github.com/cheeaun/javascript-error-logging>.

Cheers :smiley:
